version: "3"
services:
  fileserver:
    image: jiangxiyang/fileserver:1.0
    container_name: fileserver
    restart: always
    hostname: fileserver
    networks:
      - cloudStorageSystem
      
networks:
  cloudStorageSystem:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16      
