version: "3"
services:
  nginx-gateway:
    image: nginx:1.21.5
    container_name: nginx_gateway
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8888:8081
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
    networks:
      - cloudStorageSystem
    depends_on:
      - fileserverapi
  fileserverrpc:
     image: jiangxiyang/fileserverrpc:1.0
     container_name: fileserverrpc
     restart: always
     hostname: fileserverrpc
     ports:
     - "8001:8001"
     networks:
     - cloudStorageSystem
     deploy:
       mode: replicated
       replicas: 3

  fileserverapi:
    image: jiangxiyang/fileserverapi:1.0
    container_name: fileserverapi
    restart: always
    hostname: fileserverapi
    ports:
      - "8889:8889"
    depends_on:
      - fileserverrpc
    networks:
      - cloudStorageSystem
    deploy:
      mode: replicated
      replicas: 3

      
networks:
  cloudStorageSystem:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16      
