version: "3"
services:
  fileserverrpc:
     image: jiangxiyang/fileserverrpc:1.0
     container_name: fileserverrpc
     restart: always
     hostname: fileserverrpc
     ports:
     - "8001:8001"
     networks:
     - cloudStorageSystem

  fileserverapi:
    image: jiangxiyang/fileserverapi:1.0
    container_name: fileserverapi
    restart: always
    hostname: fileserverapi
    ports:
      - "8889:8889"
    depends_on:
      - fileserverrpc
    networks:
      - cloudStorageSystem
      
networks:
  cloudStorageSystem:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16      
