# log collect container

#collect the file which contains the log data which is created by server or nginx config

## elasticsearch  version: 8.5.3
## kibana version : 7.17.0
## filebeat version: 8.5.3
## zookeeper version: 3.8.0
## kafka version: 3.3.1
## go-stash version:1.0.8
services:
 filebeat:
   image: elastic/filebeat:8.5.3
   container_name: filebeat
   environment:
       TZ: Asia/Shanghai
   user: root
   restart: always
   entrypoint: "filebeat -e -strict.perms=false"  #解决配置文件权限问题
   volumes:
   - ./depoly/filebeat/conf/filebeat.yaml:/usr/share/filebeat/filebeat.yaml
   - /var/lib/docker/containers:/var/lib/docker/containers
   networks:
   -  cloudStorageSystem
   depends_on:
   -  kafka
 go-stash:
    image: go-stash:1.0.8
    container_name: go-stash
    environment:
      - TZ=Asia/Shanghai
    user: root
    restart: always
    volumes:
    - ./deploy/go-stash/etc:/app/etc
    networks:
    - cloudStorageSystem
    depends_on:
      - elasticsearch
      - kafka
     
 elasticsearch:
   image: elasticsearch:8.5.3
   container_name: elasticsearch
   user: root
   environment:
   - discovery.type=single-node
   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
   - TZ=Asia/Shanghai
   volumes:
   - ./data/elasticsearch/data:/use/share/elasticsearch/data
   restart: always
   ports:
   - 9200:9300
   - 9300:9300
   networks:
   - cloudStorageSystem
 kibana:
   image: kibana:8.5.3
   container_name: kibana
   environment:
   - elasticsearch.hosts:http://elasticsearch:9200
   - TZ=Asia/Shanghai
   restart: always
   networks:
   - cloudStorageSystem
   ports:
   - 5601:5601
   depends_on:
   - elasticsearch  

 zookeeper:
   image: zookeeper:3.8.0
   container_name: zookeeper
   environment:
     TZ: Asia/Shanghai
   restart: always
   ports:
   -  2181:2181
   networks:
   - cloudStorageSystem

 kafka:  
   image: bitnami/kafka:3.3.1
   container_name: kafka
   ports:
   - 9092:9092
   environment:
   - KAFKA_ADVERTISED_HOST_NAME=kafka
   - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
   - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
   - TZ=Asia/Shanghai
   restart: always
   volumes:
   - /var/run/docker.sock:/var/run/docker/sock
   networks:
   - cloudStorageSystem
   depends_on:
   - zookeeper

networks:
  cloudStorageSystem:
     driver: bridge
     ipam: 
       config:
       - subnet: 172.20.0.0/16

