Clusters:
- Input:
      kafka:
        Name: go-stash
        Log:
          Mode: file
        Brokers:
          - "kafka:9092"
        Topics:
        - cloudStorage-log
        Group: stash
        Conns: 3
        Consumers: 10
        Processors: 60
        MinBytes: 1048576
        MaxBytes: 10485760
        Offset: first
      Filters:
      - Action: drop
        Conditions:
        - Key: status
          Value: "503"
      - Action: remove_field
          Fields:
          - source
          - _score
          - "@metadata"
          - agent
          - ecs
          - input
          - log
          - fields
      Output:
        ElasticSearch:
          Hosts:
          - "http://elasticsearch:9200"
          Index:  "cloudStorage-{{yyyy.MM.dd}}"
          MaxChunkBytes: 5242880
          GracePeriod: 10s
          Comporess: false
          TimeZone: UTC