// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"fileServer/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/file/upload",
				Handler: uploadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/file/download",
				Handler: downloadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/file/get",
				Handler: getFileInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/file/query",
				Handler: queryFileInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/file/delete",
				Handler: deleteFileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/file/update",
				Handler: updateFileHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/file"),
		rest.WithTimeout(3*time.Second),
		rest.WithPriority(),
	)
}
