// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"cloudStorageSystem/app/CloudStorageBackend/FileServer/api/internal/svc"
	"net/http"


	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/file/upload",
				Handler: uploadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/file/download",
				Handler: downloadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/file/get",
				Handler: getFileInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/file/query",
				Handler: queryFileInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/file"),
	)
}
