// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Name     string `form:"name"`
	Password string `form:"password"`
}

type LoginRes struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	Result       string `json:"result"`
}

type RegisterReq struct {
	Name     string `from:"name"`
	Password string `from:"password"`
	Email    string `from:"email"`
}

type RegisterRes struct {
	Result string `json:"result"`
	Data   string `json:"data"`
}

type CaptchaVerifyReq struct {
	Id    string `form:"id"`
	Value string `form:"value"`
}

type CaptchaVerifyRes struct {
	Result string `json:"result"`
}
