// Code generated by goctl. DO NOT EDIT.
package types

type BaseResponse struct {
	Result  string                 `json:"result"`
	Message string                 `json:"message"`
	Data    map[string]interface{} `json:"data"`
}

func GetSuccessRep(data map[string]interface{})*BaseResponse{
	return &BaseResponse{
		Result: "true",
		Message: "获取成功",
		Data:data,
		}
}
func GetFailedRep(msg string)*BaseResponse{
	return &BaseResponse{
		Result: "fail",
		Message: msg,
	}
}

type UploadReq struct {
	MetaInfo map[string]interface{} `json:"metaInfo"`
	Data     []byte                 `form:"fileData"`
}

type DownloadReq struct {
	MetaInfo map[string]interface{} `json:"metaInfo"` //must include the location key and the
}

type FindReq struct {
	MetaInfo map[string]interface{} `json:"metaInfo"` //must include the location key
}

type QueryReq struct {
	MetaInfo map[string]interface{} `json:"metaInfo"` //mush include the owner name
}
