// Code generated by goctl. DO NOT EDIT.
package types

type BaseResponse struct {
	Result  string      `json:"result"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}
func NewDefaultRes()*BaseResponse{
	return &BaseResponse{
		Result: "true",
		Message: "操作成功",
	}
}
func (br *BaseResponse)AddData(data interface{}){
	br.Data=data
}
func( br *BaseResponse) GetFailedRep(msg string){
	br.Result= "fail"
	br.Message=msg
}

type UploadReq struct {
	MetaInfo map[string]interface{} `json:"metaInfo"`
	Data     []byte                 `form:"fileData"`
}

type DownloadReq struct {
	MetaInfo map[string]interface{} `json:"metaInfo"` //must include the location key and the
}

type FindReq struct {
	MetaInfo map[string]interface{} `json:"metaInfo"` //must include the location key
}

type QueryReq struct {
	MetaInfo map[string]interface{} `json:"metaInfo"` //mush include the owner name
}
