// Code generated by goctl. DO NOT EDIT!
// Source: fileServer.proto

package fileserver

import (
	"context"

	"cloudStorageSystem/app/CloudStorageBackend/FileServer/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FileMetaInfo = pb.FileMetaInfo
	FindFileReq  = pb.FindFileReq
	QueryFileReq = pb.QueryFileReq
	QueryFileRes = pb.QueryFileRes

	FileServer interface {
		FindOne(ctx context.Context, in *FindFileReq, opts ...grpc.CallOption) (*FileMetaInfo, error)
		QueryFiles(ctx context.Context, in *QueryFileReq, opts ...grpc.CallOption) (*QueryFileRes, error)
	}

	defaultFileServer struct {
		cli zrpc.Client
	}
)

func NewFileServer(cli zrpc.Client) FileServer {
	return &defaultFileServer{
		cli: cli,
	}
}

func (m *defaultFileServer) FindOne(ctx context.Context, in *FindFileReq, opts ...grpc.CallOption) (*FileMetaInfo, error) {
	client := pb.NewFileServerClient(m.cli.Conn())
	return client.FindOne(ctx, in, opts...)
}

func (m *defaultFileServer) QueryFiles(ctx context.Context, in *QueryFileReq, opts ...grpc.CallOption) (*QueryFileRes, error) {
	client := pb.NewFileServerClient(m.cli.Conn())
	return client.QueryFiles(ctx, in, opts...)
}
