// Code generated by goctl. DO NOT EDIT!
// Source: fileServer.proto

package server

import (
	"context"
	"fileServer/rpc/internal/logic"
	"fileServer/rpc/internal/svc"
	"fileServer/rpc/pb"
)

type FileServerServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFileServerServer
}

func NewFileServerServer(svcCtx *svc.ServiceContext) *FileServerServer {
	return &FileServerServer{
		svcCtx: svcCtx,
	}
}

func (s *FileServerServer) FindOne(ctx context.Context, in *pb.FindFileReq) (*pb.FileMetaInfo, error) {
	l := logic.NewFindOneLogic(ctx, s.svcCtx)
	return l.FindOne(in)
}

func (s *FileServerServer) QueryFiles(ctx context.Context, in *pb.QueryFileReq) (*pb.QueryFileRes, error) {
	l := logic.NewQueryFilesLogic(ctx, s.svcCtx)
	return l.QueryFiles(in)
}
